### ISSUE TITLE
Nesting and indentation

### ISSUE THREAD

**Issue by aubreywullschleger** [BTranMan/prj-rev-bwfs-dasmoto#1]
Great! Nice job with the consistent nesting and indentation in your HTML.  This makes your markup more organized and easy to read.

https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L10-L15
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L16-L21
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L22-L27

**Comment by BTranMan** [comment]
Thank you!
