### ISSUE TITLE
Attribute spacing

### ISSUE THREAD

**Issue by aubreywullschleger** [BTranMan/prj-rev-bwfs-dasmoto#2]
Simplify! Make sure you are using consistent spacing for all your attributes on your HTML elements.  It's a very small detail to consider but makes a big difference in the readability of your markup.  Lines 14, 20, 26 have a `<span>` element with a `class` attribute.  Make sure you don't have a space between the attribute and equal sign. For example, use this:

`<span class="price">`

instead of:
`<span class ="price">`

https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L14
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L20
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L26

**Comment by BTranMan** [comment]
Ah yes! I overlooked the formatting on the <span> elements - had to look that one up and did a straight copy+paste from an online resource, thanks for bringing that to my attention.
