### ISSUE TITLE
Clean CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [BTranMan/prj-rev-bwfs-dasmoto#3]
Great! Awesome job with your CSS. It's concise and consistently spaced making it easy to read. I appreciate that you used a class selector to style multiple elements at the same time. Keep it up!

https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/css/style.css#L31-L34

**Comment by BTranMan** [comment]
Thank you!
