### ISSUE TITLE
Using group selectors in CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [BTranMan/prj-rev-bwfs-dasmoto#4]
Simplify! Consider using group selectors to cut down on repeated styles even more.  I notice that you have `font-weight: bold;` repeated three times. Instead you could add a group selector for `h1`, `h2`, and `.price` and use `font-weight: bold;` in that new selector and delete the other instances of the style. Like this:
```
h1, h2, .price {
  font-weight: bold;
} 
```

https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/css/style.css#L8
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/css/style.css#L15
https://github.com/BTranMan/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/css/style.css#L32

**Comment by BTranMan** [comment]
Perfect, thanks for the suggestion. I have updated the code and will look out for this in the future!
